server {
    listen 8080;
    server_name localhost;

    # Onde os arquivos estáticos (web-data) ficarão
    root /usr/share/nginx/html;

    location / {
        # Tenta carregar arquivo estático, se não achar, manda para o Apache (app:80)
        try_files $uri $uri/ @apache;
    }

    location @apache {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}